In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
plannig_path

prev_dot = 0,0
for dot in plan:
  form_A_to_B(prev_dot, dot)
  draw
  prev_dot = dot




In [ ]:
plannig_path:
  arr = array.deepcopy

  now = 0,0


  while True
    if no 0 in arr:
      return

    next = find_the_nearest(now, arr)
    plan.append(next)
    arr. location(next) = 1
    now = next

In [ ]:
find_the_nearest()
  arr1 = asshape_deepcopy.dtype = float64

  for y in shape[0]: #Y
    for x in shape[1]: #X
      if == 0:
        arr[y, x] = dot.dis(x, y) 
      else
        = DOT.MAX

  return where.min

In [ ]:
dot.dis(self, x, y):
  if self.xy==xy
    return 0
  vec_x = x - self.x
  vec_y = y - self.y # 指向被减数
  
  v_x_ = vec_y
  v_y_ = -vec_x # 顺时针旋转90度

  perfer = (math.atan2(v_y_,v_x_) + math.pi) / math.pi / 2

  return abs(vec_x) + abs(vec_y) + perfer

In [ ]:


MAX_DISTENCE = 9999  # 对角线最远, 320 + 120 = 440


class Printer:
    pass


class Dot:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y

    def dist(self, x, y):
        if x == self.x and y == self.y:
            return 0

        # 得出由self指向(x, y)的向量
        vec_x = x - self.x
        vec_y = self.y - y
        # y要反转, 因为是向下生长的

        # 顺时针旋转90度, 但是y反转所以转180度, 反而是逆时针90
        v_x_ = -vec_y  # v_x_ => Vec x'
        v_y_ = vec_x
        
        # 但是由于0会映射到2π上去, 所以要多写个if
        if vec_x == 0 and vec_y > 0:
          perfer = 0
        else:
          perfer = (math.atan2(v_y_, v_x_) + math.pi) / math.pi / 2

        return abs(vec_x) + abs(vec_y) + perfer



In [ ]:
dot = Dot(2,2)

"""for y in range(5):
  for x in range(5):
    print(x, ", ", y, " : ", end="")
    print(dot.dist(x, y))
"""

print(dot.dist(2, 0))
print(dot.dist(1, 1))
print(dot.dist(0, 2))
print(dot.dist(1, 3))
print(dot.dist(2, 4))
print(dot.dist(3, 3))
print(dot.dist(4, 2))
print(dot.dist(3, 1))

2
2.125
2.25
2.375
2.5
2.625
2.75
2.875


In [ ]:
a = Dot(2,2)
b = a
c = b
print(c.x, c.y, a.x, a.y)

2 2 2 2


In [ ]:
ls = np.arange(12)
ls = ls.reshape(3, 4)
print(ls.shape)
x, y = np.where(ls == np.max(ls))
print(ls)
#print()

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
test = Dot(0, 120)
print(test.dist(1,0))

1   120
121.99867373950747
